- name: conditions demo
  hosts: local
  connection: local
  vars:
    number: 56
  tasks:
  - name: print if number is lessthan or equal to 100
    ansible.builtin.debug:
      msg: "given number {{number}} is lessthan or equal to 100"  
    when: number < 100

  - name: print if number is greaterthan 100
    ansible.builtin.debug:
      msg: "given number {{number}} is greaterthan 100"
    when: number > 100  