- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh, joseph, raheem"
  tasks:
   - name: check undefined variable
     ansible.builtin.debug:
       msg: "Hello, {{ person | default('Ramesh') }}"

   - name: print names
     ansible.builtin.debug:
       msg: "hello {{persons | split(',') }}"

   - name: convert map into list 
     vars:
       course:
         name: ansible
         duration: 10HR
         trainer: samrin
     ansible.builtin.debug:
       msg: "course info:{{ course | dict2items  }}"     